### ISSUE TITLE
TypeError: Patterns must be a string or an array of strings

### ISSUE THREAD

**Issue by bluedusk** [postcss/autoprefixer#1030]
Got this error: 
>    TypeError: Patterns must be a string or an array of strings

Error Message Detail:

```
TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\globby\index.js:15:9)
    at generateGlobTasks (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\globby\index.js:21:2)
    at module.exports (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\globby\index.js:73:15)
    at Promise.resolve.then (D:\WorkSpace\CSS\css_advance_course\Natours\starter\node_modules\postcss-cli\index.js:55:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

When I try to run this with npm script:

>    "postcss --use autoprefixer -b 'last 10 versions' input.css -o output.css"

System Environment:
>     
    System: Win7 64
    Node: v8.11.1
    NPM: 5.6.0
    "autoprefixer": "^8.4.1",
    "postcss-cli": "^5.0.0"

**Comment by ai** [comment]
Sorry. According to stack trace it is not related to Autoprefixer.

Can you add a issue in postcss-cli to improve error report? Seems like you have some mistake in postcss-cli, but there problem is that postcss-cli doesn't report it well.

Please mention me in that issue.
