### ISSUE TITLE
`css.source && css.source.input.file` TypeError: Cannot read property 'source' of undefined (webpack 1.x)

### ISSUE THREAD

**Issue by Dan503** [postcss/autoprefixer#1108]
I'm getting the following error:

```
C:\xxxxx\node_modules\autoprefixer\lib\autoprefixer.js:97
      from: css.source && css.source.input.file,
                ^

TypeError: Cannot read property 'source' of undefined
    at Compiler.plugin (C:\Users\daniel.tonon\Sites\RSL
Queensland\RSL-Front-End-git\node_modules\autoprefixer\lib\autoprefixer.js:97:17)
    at Compiler.apply (C:\xxxxx\node_modules\tapable\lib\Tapable.js:164:16)
    at WebpackOptionsApply.process (C:\xxxxx\node_modules\webpack\lib\WebpackOptionsApply.js:62:18)
    at webpack (C:\xxxxx\node_modules\webpack\lib\webpack.js:22:48)
    at C:\xxxxx\node_modules\webpack\lib\webpack.js:15:11
    at Array.map (<anonymous>)
    at webpack (C:\xxxxx\node_modules\webpack\lib\webpack.js:14:40)
    at processOptions (C:\xxxxx\node_modules\webpack\bin\webpack.js:152:17)
    at Object.<anonymous> (C:\xxxxx\node_modules\webpack\bin\webpack.js:192:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

I've atttached a zip with my webpack config and package.json files

You will find the autoprefixer import in the webpack-helpers file.

[bug-related-files.zip](https://github.com/postcss/autoprefixer/files/2364810/bug-related-files.zip)

**Comment by ai** [comment]
1. Move Browsers to `browserslist` config in `package.json`.
2. I didn’t find `postcss-loader` in Webpack config. How do you run Autoprefixer?

**Comment by Dan503** [comment]
It's in the `webpack-helpers.js` file.

**Comment by Dan503** [comment]
It think it says `postcss` under `loaders`.

**Comment by ai** [comment]
Sorry, I forgot all Webpack 1.x APIs. Maybe there is a conflict between old `postcss-loader` (new loader I think support only latest Webpack) and new Autoprefixer? Because this error seems like that something is wrong with AST or plugin API.

I am not sure that I want to support Webpack 1.x (but I will accept PR if you will find the exact problem).

**Comment by Dan503** [comment]
Yeah fair enough.

I'm running into a whole heap of issues trying to work within a webpack 1.x framework.

I was hoping I could still use Autoprefixer on the project to give me access to CSS Grid. No Grid for me then :(

**Comment by ai** [comment]
Try to look at `npm ls` what PostCSS version is used.

To be honest, your Webpack config is not so big. It will be more easy to migrate to latest Webpack. It could take less time.
