### ISSUE TITLE
TypeError when plugin used after postcss-tidy-columns

### ISSUE THREAD

**Issue by goodguyry** [postcss/autoprefixer#1115]
I am the creator of PostCSS Tidy Columns. I fully understand this is likely an issue with my plugin, but I can't figure it out.

When using Autoprefixer after Tidy Columns I get the following error:

```
TypeError: node.each is not a function

      at <input css 1>:1:83
      at Processor.disabled (node_modules/autoprefixer/lib/processor.js:424:14)
      at node_modules/autoprefixer/lib/processor.js:286:20
      at callback (node_modules/postcss/lib/container.es6:161:18)
      at callback (node_modules/postcss/lib/container.es6:110:18)
      at Rule.callback [as each] (node_modules/postcss/lib/container.es6:76:16)
      at Rule.each (node_modules/postcss/lib/container.es6:107:17)
      at walk (node_modules/postcss/lib/container.es6:121:24)
      at AtRule.callback [as each] (node_modules/postcss/lib/container.es6:76:16)
      at AtRule.each (node_modules/postcss/lib/container.es6:107:17)
      at walk (node_modules/postcss/lib/container.es6:121:24)
```

When Autoprefixer is used before Tidy Columns everything works as expected.

If I log `node` in `processor.js:424`:
- Autoprefixer first: `node` is a Declaration 👎
- Autoprefixer last: `node` is a Rule 👍

I have a test here.
https://github.com/goodguyry/postcss-tidy-columns/blob/plugin-checks/test/plugins.test.js

I recently upgraded to the most recent versions of PostCSS and Autoprefixer hoping that was the issue, but it was not.

I've found no issues with any other plugins, which only makes this more baffling.

Thank you for your time. I appreciate any light you can shed on this, as it's driving me crazy 😕

**Comment by ai** [comment]
Yeap, maybe AST is broken. It is OK, we can fix it.

As you can see here: Autoprefixer runs `node.each` only if `node.nodes` exists. `node.nodes` mean that the node should be extended from `Container`.

Maybe you set `#nodes` to `Declaration` somewhere?

**Comment by ai** [comment]
Yeap. I found https://github.com/goodguyry/postcss-tidy-columns/blob/plugin-checks/lib/cleanClone.js#L11

Here you set `nodes` to every node, even to `Declaration`. I suggest to replace it to:

```js
const cleaner = { }
if (node.nodes) cleaner.nodes = []
const clonedNode = node.clone(Object.assign(overrides, cleaner));
```

**Comment by goodguyry** [comment]
Thank you so much! I really appreciate you taking the time.
