### ISSUE TITLE
Gulpfile not working

### ISSUE THREAD

**Issue by Mikeskay** [postcss/autoprefixer#1205]
Hi Guys, 

I've been following a git web developer video course and I'm having trouble with the gulp watch bit of the video. As the video is few years old, it seems the code in the video is out of date so I had to modify the code a little. I have gotten to this part but when I write my code in the gulpfile I get the error below in my command line.

**This is my gulpfile code i have written :**

var gulp = require('gulp'),
watch = require('gulp-watch'),
postcss = require('gulp-postcss'),
autoprefixer = require('autoprefixer'),
cssvars = require('postcss-simple-vars'),
nested = require('postcss-nested'),
cssImport = require('postcss-import');

gulp.task('styles', function(){
gulp.src('./app/assets/styles/styles.css')
.pipe(cssImport())
.pipe(cssvars())
.pipe(nested())
.pipe(autoprefixer())
.pipe(gulp.dest('./app/temp/styles'));
});

gulp.task('watch', function() {

gulp.watch('./app/assets/styles/**/*.css', gulp.series('styles'));

});

**but for some reason I see this on my command line:**

BP:travel-site michaelk$ gulp watch
[15:31:32] Using gulpfile ~/Desktop/sites /travel-site/gulpfile.js
[15:31:32] Starting 'watch'...
[15:31:38] Starting 'styles'...
[15:31:38] 'styles' errored after 17 ms
[15:31:38] TypeError: dest.on is not a function
at DestroyableTransform.Readable.pipe (/Users/michaelk/Desktop/sites /travel-site/node_modules/readable-stream/lib/_stream_readable.js:564:8)
at /Users/michaelk/Desktop/sites /travel-site/gulpfile.js:11:4
at taskWrapper (/Users/michaelk/Desktop/sites /travel-site/node_modules/undertaker/lib/set-task.js:13:15)
at bound (domain.js:395:14)
at runBound (domain.js:408:12)
at asyncRunner (/Users/michaelk/Desktop/sites /travel-site/node_modules/async-done/index.js:55:18)
at process._tickCallback (internal/process/next_tick.js:61:11)?

**Comment by Dan503** [comment]
Your Gulp config is incorrect.

See this section of the documentation:

https://github.com/postcss/autoprefixer/blob/master/README.md#gulp

**Comment by ai** [comment]
@Mikeskay you need to use `gulp-postcss` in `gulp.task('styles'`.

**Comment by Mikeskay** [comment]
Thank you for your help guys, really appreciated  - I will give it a go when I get home. 

@ai @Dan503
