### ISSUE TITLE
ERROR: Unknown version 67 of android

### ISSUE THREAD

**Issue by mbaric1** [postcss/autoprefixer#1265]
.browserlistrc
```
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 11
```

Error
`ng build frontend --prod`

```
ERROR: Unknown version 67 of android
An unhandled exception occurred: Unknown version 67 of android
See "C:\Users\user\AppData\Local\Temp\ng-tM13Xi\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! frontend@1.0.0 `ng build frontend --prod`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the frontend@1.0.0.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-11-21T16_10_29_385Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@1.0.0 
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@1.0.0
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-11-21T16_10_29_394Z-debug.log
```

debug.log
```
[error] BrowserslistError: Unknown version 67 of android
    at Function.select (C:\Projects\frontend\node_modules\autoprefixer\node_modules\browserslist\index.js:931:17)
    at C:\Projects\frontend\node_modules\autoprefixer\node_modules\browserslist\index.js:252:33
    at Array.reduce (<anonymous>)
    at resolve (C:\Projects\frontend\node_modules\autoprefixer\node_modules\browserslist\index.js:234:18)
    at browserslist (C:\Projects\frontend\node_modules\autoprefixer\node_modules\browserslist\index.js:358:21)
    at Browsers.parse (C:\Projects\frontend\node_modules\autoprefixer\lib\browsers.js:66:12)
    at new Browsers (C:\Projects\frontend\node_modules\autoprefixer\lib\browsers.js:48:26)
    at loadPrefixes (C:\Projects\frontend\node_modules\autoprefixer\lib\autoprefixer.js:97:20)
    at plugin (C:\Projects\frontend\node_modules\autoprefixer\lib\autoprefixer.js:108:20)
    at LazyResult.run (C:\Projects\frontend\node_modules\postcss\lib\lazy-result.js:295:14)
```
npm ls | grep autoprefixe
+-- autoprefixer@9.7.2

npm ls | grep postcss
+-- postcss@7.0.23
+-- postcss-cli@6.1.3
+-- postcss-normalize@8.0.1

Fixed issue by installing `"caniuse-lite": "^1.0.30001011",` as a dev dependency, but that is not real solution.

**Comment by ai** [comment]
Call `npm update` to update `caniuse-lite` deeply in the dependency tree.

**Comment by mbaric1** [comment]
Still able to reproduce it on clean install

1. rm -rf node_modules/ package-lock.json
2. npm cache clear --force
3. npm i
4. ng build project --prod

Even if 
5. npm update

Error above still remains.

**Comment by Dan503** [comment]
It often helps if you can create a reduced test case repo here on GitHub which has the minimum amount of code needed to replicate the issue.

**Comment by aifrim** [comment]
Same problem happens with autoprefixer@9.7.4.
Works if you use autoprefixer@9.0.6.

**Comment by ai** [comment]
It happens if you have different versions of `caniuse-lite` or `browserslist` in different branches of `npm ls`. It could be fixed with `npm update`.
