### ISSUE TITLE
Build Error in NPM Release Step Azure DevOps:[object object] Is Not A Post CSS Plugin

### ISSUE THREAD

**Issue by souryachakrabarti** [postcss/autoprefixer#1390]
This issue is occurring in the build step of NPM release.We tried hardcoding the version from previous NPM releases but it did not work.
Exception:
BUILD ERROR  in NPM release: [object Object] is not a PostCSS plugin
Error: [object Object] is not a PostCSS plugin
 at Processor.normalize (D:\agent1\_work\r71\a\swagger-codegen\node_modules\postcss\lib\processor.js:145:15)
 at new Processor (D:\agent1\_work\r71\a\swagger-codegen\node_modules\postcss\lib\processor.js:51:25)
 at postcss (D:\agent1\_work\r71\a\swagger-codegen\node_modules\postcss\lib\postcss.js:73:10)
  at createPostCssProcessor (D:\agent1\_work\r71\a\swagger-codegen\node_modules\ng-packagr\lib\ng-v5\entry-point\resources\stylesheet.transform.js:73:12)
 at Object.<anonymous> (D:\agent1\_work\r71\a\swagger-codegen\node_modules\ng-packagr\lib\ng-v5\entry-point\resources\stylesheet.transform.js:36:30)

**Comment by ai** [comment]
You have PostCSS 7 somewhere in build pipeline. Check `npm ls | grep postcss` output.

Downgrade PostCSS plugins or fund a way to update to PostCSS 8.
