### ISSUE TITLE
NameError, processor.rb while working with compass and bootstrap/sass

### ISSUE THREAD

**Issue by Doev** [postcss/autoprefixer#394]
I have installed autoprefixer like descripted here: https://github.com/postcss/autoprefixer#compass

Line 49 in config.rb is:

File.open(file, 'w') { |io| io << AutoprefixerRails.process(css) }

Error:
```
https://github.com/postcss/autoprefixer#compass
  /var/lib/gems/1.9.1/gems/autoprefixer-rails-5.0.0.1/lib/autoprefixer-rails.rb:12:in `process'
  [...]/config.rb:49:in `block (2 levels) in get_binding'
  [...]/config.rb:49:in `open'
  [...]/config.rb:49:in `block in get_binding'
  /var/lib/gems/1.9.1/gems/sass-3.2.19/lib/sass/callbacks.rb:60:in `[]'
  /var/lib/gems/1.9.1/gems/sass-3.2.19/lib/sass/callbacks.rb:60:in `block in run_stylesheet_saved'
  /var/lib/gems/1.9.1/gems/sass-3.2.19/lib/sass/callbacks.rb:60:in `each'
  /var/lib/gems/1.9.1/gems/sass-3.2.19/lib/sass/callbacks.rb:60:in `run_stylesheet_saved'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/configuration/inheritance.rb:164:in `run_stylesheet_saved'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/configuration/inheritance.rb:166:in `run_stylesheet_saved'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:144:in `compile'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:118:in `compile_if_required'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:103:in `block (2 levels) in run'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:101:in `each'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:101:in `block in run'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:126:in `timed'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/compiler.rb:100:in `run'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/commands/watch_project.rb:147:in `recompile'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/commands/watch_project.rb:68:in `perform'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/commands/base.rb:18:in `execute'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/commands/project_base.rb:19:in `execute'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/bin/compass:30:in `block in <top (required)>'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/bin/compass:44:in `call'
  /var/lib/gems/1.9.1/gems/compass-0.12.6/bin/compass:44:in `<top (required)>'
  /usr/local/bin/compass:23:in `load'
  /usr/local/bin/compass:23:in `<main>'
```
config.rb:
```
require 'bootstrap-sass'
# Require any additional compass plugins here.

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "../public/css"
sass_dir = "sass"
images_dir = "../public/img"
javascripts_dir = "../public/js"

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

output_style = :compact

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false

line_comments = false

# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass

# ############
#
# autoprefixer
#

require 'autoprefixer-rails'

on_stylesheet_saved do |file|
  css = File.read(file)
  map = file + '.map'

  if File.exists? map
    result = AutoprefixerRails.process(css,
      from: file,
      to:   file,
      map:  { prev: File.read(map), inline: false })
    File.open(file, 'w') { |io| io << result.css }
    File.open(map,  'w') { |io| io << result.map }
  else
    File.open(file, 'w') { |io| io << AutoprefixerRails.process(css) }
  end
end
```

**Comment by ai** [comment]
You should use Gulp if you have issues like this.

Autoprefixer from `config.rb` is a hack, only for cases when developers can’t use modern build tools.

**Comment by ai** [comment]
Problem in your issue, that it goes somewhere from Sass. Autoprefixer Rails [has a tests](https://github.com/ai/autoprefixer-rails/blob/master/spec/compass_spec.rb) for `config.rb`, so here is environment issue.

Of course, we can spent a day to find source of problem. But what it is a point if it is strong hack and there is no future to build styles by `compass compile` when we have so many awesome gulp\grunt plugins :).

**Comment by ai** [comment]
I added mention about Gulp into Autoprefixer Compass section https://github.com/postcss/autoprefixer/commit/8738cc0a28947b06d9fcc93f907ebedd96888104
