### ISSUE TITLE
nodejs 4.0.0 support 

### ISSUE THREAD

**Issue by prog666** [postcss/autoprefixer#519]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
 at afterTransform (/projectfolder/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
    at Immediate.TransformState.afterTransform (/projectfolder/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at Immediate.immediate._onImmediate (timers.js:423:18)
    at processImmediate [as _immediateCallback] (timers.js:371:17)

**Comment by ai** [comment]
It is error inside Gulp and Stream. So I can't fix it in core Autoprefixer. Ask `gulp-autoprefixer` author (it is non-official way, so I can't help you here), because all Stream code is located there.

**Comment by prog666** [comment]
ok, thanks

**Comment by simonbusborg** [comment]
For people wondering, downgrade node to `0.12.2` to make it work again.

**Comment by prog666** [comment]
0.12.7 works fine, i use nvm for this

**Comment by DamieUk** [comment]
- delete node modules  "rm -rf node_modules"
- reinstall node modules "npm install"

- then go to 'gulp-combine-media-queries' and comment line "file.contents = new Buffer(cssJson)"
- run gulp.

That worked for me lots of times.
