### ISSUE TITLE
Syntax error: unexpected reserved word 'import'.

### ISSUE THREAD

**Issue by ThorntonStuart** [postcss/autoprefixer#525]
Hi there. I added autoprefixer into my gulpfile this morning and was met with an error upon running my gulp command which said there was a syntax error somewhere within the plugin. 

As this issue is with a reserved word I should imagine that this is something going wrong within my own build system, but I've looked everywhere and can't find this problem replicated so I thought I'd make sure. This is the error I get:

```
/Users/StuartThornton/Documents/Coding/Sites/personal-site/node_modules/gulp-autoprefixer/node_modules/postcss/lib/postcss.es6:1
(function (exports, require, module, __filename, __dirname) { import Declarati
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .es6] (/Users/StuartThornton/Documents/Coding/Sites/personal-site/node_modules/gulp-autoprefixer/node_modules/postcss/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/StuartThornton/Documents/Coding/Sites/personal-site/node_modules/gulp-autoprefixer/node_modules/postcss/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

And this is my gulpfile.js.

```
var gulp = require('gulp');
var uglify = require('gulp-uglify');
var sass = require('gulp-ruby-sass');
var livereload = require('gulp-livereload');
var prefix = require('gulp-autoprefixer')

function errorLog(error) {
	console.error.bind(error);
	this.emit('end');
}

// Scripts Task
// Uglifies
gulp.task('scripts', function(){
	gulp.src('js/*.js')
	.pipe(uglify())
	.on('error', errorLog)
	.pipe(gulp.dest('minjs'))
});

//SASS Task
//Compiles SASS
gulp.task('sass', function(){
	return sass('scss/*.scss', { style: 'compressed' })
	.on('error', errorLog)
	.pipe(prefix('last 2 versions'))
	.pipe(gulp.dest('./css'))
	.pipe(livereload());
});

// Watch Task
// Watches JS and CSS
gulp.task('watch', function(){
	livereload.listen();
	gulp.watch('js/*.js', ['scripts']);
	gulp.watch('scss/*.scss', ['sass']);
});

gulp.task('default', ['scripts', 'sass', 'watch',]);
```

**Comment by ben-eb** [comment]
It's a PostCSS issue, please upgrade to 5.0.8. :smile:

More info: https://github.com/postcss/postcss/issues/582

**Comment by ThorntonStuart** [comment]
Much appreciated!
