### ISSUE TITLE
gulp-autoprefixer promise is not defined

### ISSUE THREAD

**Issue by satya5561** [postcss/autoprefixer#545]
got this error 

gulp-autoprefixer promise is not defined.

[21:38:46] gulp-inject 22 files into app.scss.
Process terminated with code 8.
D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\postcss\lib\lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\postcss\lib\lazy-result.js:152:31)
    at LazyResult.then (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\postcss\lib\lazy-result.js:75:21)
    at DestroyableTransform._transform (D:\Projects\oges_web\node_modules\gulp-autoprefixer\index.js:24:6)
    at DestroyableTransform.Transform._read (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:326:12)
    at writeOrBuffer (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (D:\Projects\oges_web\node_modules\gulp-autoprefixer\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:239:11)
    at write (D:\Projects\oges_web\node_modules\gulp-sass\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (D:\Projects\oges_web\node_modules\gulp-sass\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)

**Comment by TrySound** [comment]
@satya5561 You use node 0.10 or less. Promises are supported since 0.12. If you don't able to update. You can install polyfill before all postcss requires. For example [es6-promise](https://github.com/jakearchibald/es6-promise)

**Comment by anderskleve** [comment]
I get the same error, running node version 5.3.0.
