### ISSUE TITLE
Failed to load the autoprefixer package

### ISSUE THREAD

**Issue by luxyu** [postcss/autoprefixer#680]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [autoprefixer](https://github.com/postcss/autoprefixer) package, v6.3.6

### Stack Trace

Failed to load the autoprefixer package

```
At Cannot find module 'coffee-script'

Error: Cannot find module 'coffee-script'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\yuhon\.atom\packages\autoprefixer\index.js:1:80)
    at Module._compile (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\yuhon\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autoprefixer, v6.3.6

# Dev
No dev packages
```

**Comment by ai** [comment]
Did you use Atom plugin or Autoprefixer from npm via CLI?
