### ISSUE TITLE
data.json parse error  

### ISSUE THREAD

**Issue by dman777** [postcss/autoprefixer#711]
in gulp(fountain webapp), using:

```
  "name": "autoprefixer",
  "version": "6.4.1",
```

Running autoprefixer gives:

```
[20:08:07] Loading /var/www/one-drop-demo/gulp_tasks/build.js
module.js:453
    throw err;
    ^

SyntaxError: /var/www/one-drop-demo/node_modules/autoprefixer/node_modules/caniuse-db/data.json: Unexpected token n
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module._load (/var/www/one-drop-demo/node_modules/gulp-hub/lib/load-subfile.js:26:32)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/one-drop-demo/node_modules/autoprefixer/node_modules/browserslist/index.js:1:77)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

Looking at the `data.json`, it's to big to find where the parse issue would be.

**Comment by ai** [comment]
Sorry, this issue is not relevant to Autoprefixer, because this error is about syntax error in other npm package — `caniuse-db` ;).

But I tested Autoprefixer with latest Can I Use. Everything is fine. So I think you my have broken npm cache or something like it. Remove `node_modules` and `~/.npm` and start `npm install` again.

**Comment by dman777** [comment]
Ah, thanks! Sorry about the trouble :)
