### ISSUE TITLE
throw new Error('Change `browser` option to `browsers` in Autoprefixer');?

### ISSUE THREAD

**Issue by blaasvaer** [postcss/autoprefixer#752]
I'm suddenly getting this when running gulp ... after updating my node. And then updating Autoprefixer.

I'm using node V6.9.2, npm V4.0.3 and gulp V3.9.1 ... any idea what broke?

**Comment by blaasvaer** [comment]
The problem is: I'm not using Autoprefixer ... but "some" module has it as a dependency.

**Comment by blaasvaer** [comment]
And now I'M asked to change some options in the module?

**Comment by ai** [comment]
Get error message with stacktrace and report issue to broken dependency.

**Comment by blaasvaer** [comment]
Thanks for that. But what exactly do you mean by that? A LOT was assumed in that comment ...

**Comment by blaasvaer** [comment]
Reporting this:

    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:108:14

**Comment by ai** [comment]
Could you show full output and show your gulpfile and exactly task name, which is broken.

**Comment by blaasvaer** [comment]
OK, the monkey is in the room, found the bugger in a copied snippet (don't just copy stuff ... right?).

Sorry 'bout that. Can remove thread.
