### ISSUE TITLE
Module build failed: BrowserslistError: Unknown browser query `op_mini all`

### ISSUE THREAD

**Issue by albertolive** [postcss/autoprefixer#768]
Hi,

We're having this problem with autoprefixer without changed anything in our project.

We use postcss with webpack:

    postcss: function () {
    return [require('autoprefixer')({
      browsers: ['last 4 versions']
    })];
  }

If we change that code and put it to *package.json* it works.

_EDIT_: The problem is when we do an *npm install*. We have changed it to yarn and it works.

Any suggestion?

`ERROR in ./~/css-loader?minimize&-autoprefixer!./~/sass-loader?outputStyle=expanded!./~/postcss-loader!./src/components/FormElements/_FormElements.scss
Module build failed: BrowserslistError: Unknown browser query `op_mini all`
    at error (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/browserslist/index.js:23:15)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/browserslist/index.js:90:13
    at Array.forEach (native)
    at browserslist (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/browserslist/index.js:62:16)
    at isSupported (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/caniuse-api/dist/index.js:75:10)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:87:66
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/selectors/container.js:170:26
    at Selector.each (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Selector.walk (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/selectors/container.js:173:31
    at Root.each (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Root.walk (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
    at Processor.func (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:80:17)
    at Processor.process (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-selector-parser/dist/processor.js:34:14)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:121:12
    at Array.every (native)
    at ensureCompatibility (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:77:22)
    at canMerge (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/index.js:74:44)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/index.js:222:24
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/container.js:113:34
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/container.js:71:26
    at Root.each (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/container.js:58:22)
    at Root.walk (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/container.js:70:21)
    at Root.walkRules (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/container.js:111:25)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss-merge-rules/dist/index.js:274:13
    at LazyResult.run (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/lazy-result.js:201:20)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/lazy-result.js:129:15)
    at /var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/var/lib/jenkins/workspace/Deploy Webmanager/node_modules/postcss/lib/lazy-result.js:129:15)
 @ ./src/components/FormElements/_FormElements.scss 4:14-228`

**Comment by ai** [comment]
`op_mini all` is a valid query right now, you can check it in [online demo](http://browserl.ist/?q=op_mini+all).

I think some library use old Browserslist.
