### ISSUE TITLE
Error: Cannot find module 'caniuse-db/features-json/css3-cursors-newer.json'

### ISSUE THREAD

**Issue by nmaxcom** [postcss/autoprefixer#782]
```bash
[21:28:44] nmaxcom@stg > /the/path >> master± $ gulp
module.js:472
    throw err;
    ^

Error: Cannot find module 'caniuse-db/features-json/css3-cursors-newer.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/the/path/node_modules/autoprefixer/data/prefixes.js:379:18)
    at Object.<anonymous> (/the/path/node_modules/autoprefixer/data/prefixes.js:655:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

I've tried reinstaling, upgrading npm... the whole tour. I only use it in a 'styles' gulp function.

Nevertheless, if I don't call this function at all, and the only appearance in my `gulpfile.js` is `autoprefixer = require('gulp-autoprefixer')`, it'll still show the exact same error.

```
gulp -v
[21:40:04] CLI version 3.9.1
[21:40:04] Local version 3.9.1
node -v
v7.4.0
npm -v
4.1.2

"gulp-autoprefixer": "^3.1.1"
```

**Comment by ai** [comment]
Sorry, I will close it because this error is part of your environment.

But my suggestion:

1. Try `gulp-postcss` and `autoprefixer` instead of `gulp-autoprefixer` to get latest Autoprefixer.
2. Remove `~/.npm`, `node_modules/` and run `npm install` again.

**Comment by nmaxcom** [comment]
I'll try those. Why are so sure it's my environment? If that were the case, how would suggestion 1 help?

Thanks for helping.

**Comment by ai** [comment]
@nmaxcom environment because it is connected with `npm`, not with `autoprefixer` code itself.

`gulp-autoprefixer` is just a unofficial way and we even don’t support it.
