### ISSUE TITLE
Cannot read property 'map' of undefined after upgrading to 7.1.2

### ISSUE THREAD

**Issue by tinovyatkin** [postcss/autoprefixer#858]
Node 8.1.3, worked perfectly with 7.1.1, resulting in errors after upgrade

```
[11:47:38] [Postcss] TypeError: Cannot read property 'map' of undefined
    at _loop (/Users/tino/Repos/engine/node_modules/autoprefixer/lib/prefixes.js:116:36)
    at Prefixes.select (/Users/tino/Repos/engine/node_modules/autoprefixer/lib/prefixes.js:171:13)
    at new Prefixes (/Users/tino/Repos/engine/node_modules/autoprefixer/lib/prefixes.js:75:48)
    at loadPrefixes (/Users/tino/Repos/engine/node_modules/autoprefixer/lib/autoprefixer.js:71:26)
    at plugin (/Users/tino/Repos/engine/node_modules/autoprefixer/lib/autoprefixer.js:78:24)
    at LazyResult.run (/Users/tino/Repos/engine/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/tino/Repos/engine/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/tino/Repos/engine/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/tino/Repos/engine/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/tino/Repos/engine/node_modules/postcss/lib/lazy-result.js:197:22)
```

**Comment by tinovyatkin** [comment]
My PostCSS 6.0.6 plugin configuration in case you need it:

```js
const postCssPlugins = [
  atImport(),
  customProperties(),
  customSelectors(),
  apply(),
  calc(),
  customMedia(),
  colorFunction(),
  matches(),
  selectorNot(),
  nesting(),
  minmax(),
  mqpacker(),
  autoprefixer({
    browsers: ['> 1%', 'last 2 versions', 'Firefox ESR'],
  }),
];
```

**Comment by XhmikosR** [comment]
@tinovyatkin: how did you solve your error? I'm getting a TypeError myself, not the same as you do, but I wonder if something similar is the cause.

**Comment by kasperbaago** [comment]
@tinovyatkin Also getting this error, how did you solve it? :/
